- src/templates/Home/HomeVideo/HomeVideo.module.scss
Ensure header video always covers 100vw/100vh, even in browsers without `object-fit` support (or those with questionable support, like Edge)
> Fix header video on IE11/Edge

- netlify.toml
Redirect `/projects` to `#projects` instead of 404
Will go to `/` as the redirect doens't seem to support internal links
> Fix /projects 404 to redirect

- src/components/Footer/Footer.js
- src/utils/checkAndroid.js
- src/utils/checkIOS.js
- src/utils/checkIosVersion.js
- src/utils/copyClipboard.js
To differentiate between ios/android/tablet for a desktop only feature (well, copy to clipboard can also be used on non desktop, beside the point).
This will now check on what type of device you are and if it is a mobile/tablet (android|ios). It would fallback to the default behavior. For our usage now, it is the behavior of opening the defaulted email client of the device
> Check on ismobile or tablet for clipboard copy desktop only feature

- src/templates/Studio/Recruitee/Recruitee.js
Close the joboffer if the hash changed (emptied). To accomodate native browser history return
> Close the joboffer if you return using browser navigation

- src/templates/Home/ProjectList/IntermittentBlock/IntermittentBlock.module.scss
- src/templates/Home/ProjectList/ProjectList.module.scss
Due to the `vw` based margin and padding the spacing around the quotes on the homepage did not have enough spacing around it. I've opted to specify a fixed `px` size for mobile as specified by Ben.
> Increase spacing around quote on the homepage

- src/components/Footer/Footer.js
- src/components/Footer/Footer.module.scss
- src/components/Layout/Layout.js
- src/components/Toast/Toast.js
- src/components/Toast/Toast.module.scss
- src/templates/Studio/SkillBlock/SkillBlock.js
- src/templates/Studio/SkillBlock/SkillBlock.module.scss
- src/templates/Studio/Studio.js
- src/utils/context/AppContext.js
- src/utils/hooks/useToastVisiblity.js
Before due to the parallax (perspective property) the toast didn't show up anymore. It seems like the property `perpective` will create it's own containment element e.g. like `position: relative`. I've put the toast up a level now instead and have the parent track the state.
Also thought about using `Context` but feels like over-engineering at this point as we are only using it on the same page for two interactions.
Context also re-renders everything either way (depending on the implementation ofc) so this shouldn't be too different. Pray tell if it differs
> Fix showing the toast on desktop size

- src/api/videos/getVideoData.mjs
Allow Dato to supply a video ID directly, not a URL.
> Support supplying ID directly from Dato

- src/components/Carousel/Carousel.tsx
- src/pages/studio/index.tsx
Studio impression data, unlike most other slide data, does not nest image data within an `image` property. As a result, slider is currently broken on studio page.
**Steps to test **
1.  Currently the office photo slider on the Studio page does not show any images
2. Check that the slider now displays images correctly on the Studio page
> Format studioImpression data correctly

- src/components/Carousel/Carousel.module.css
- disable pointer events in hidden images in carousel
- Go on the project page
- Switch between slides on the carousels with images
- Right click -> Open image in new tap
- The opened image should always be the one you currently see on the carousel
> Carousel Layering

- src/api/QUERIES.js
- src/components/ProjectDetail/ContentBlock/ContentBlock.tsx
- src/types.ts
This MR adds support for linking directly to specific content blocks on a page, by appending a "#anchor" anchor ID to the end of a URL.
For example: 
https://random.studio/projects/fluid-forms-for-ecco-x-the-north-american-pavilion will go to the top of the Ecco page
https://random.studio/projects/fluid-forms-for-ecco-x-the-north-american-pavilion#store will jump to the image of a store at the bottom of the page
Anchor IDs are completely optional, but can be provided via the CMS when creating/editing a block.
1.  Using the preview link, visit the Ecco page. It will open at the top
2. Append "#store" and hit enter. The page will jump to and align to the top of the screen the photo of the store front
> Add support for block anchors

- src/api/QUERIES.js
- src/components/ProjectDetail/Credits/Credits.module.scss
- src/components/ProjectDetail/Credits/Credits.tsx
- src/components/ProjectDetail/ProjectDetail.tsx
- src/pages/projects/[slug]/index.tsx
This MR adds support to project pages for linking to external project live/archive pages. This is particularly useful for web projects, where we have not historically been able to link directly to them before.
This ties in to separate work being done to publish archive versions of lost digital projects, via *.archive.random.studio.
1.  Visit the Chloe project
2. Below the credits block, there is a new 'View website' link that links to an archived copy of the A Season in Hope campaign site
> Add support for external website/archive URLs

- package.json
- src/components/Carousel/Carousel.module.css
- src/components/Carousel/Carousel.tsx
- src/components/Layout/Layout.js
- src/components/ProjectList/Filters/Filters.js
- src/components/SustainabilitySection/SustainabilitySection.js
- src/utils/classNames.js
When carousel images' aspect ratios do not match, the carousel height will vary. This can result in the images overlapping the number/pagination indicator, or a varying margin height above the pagination.
As agreed, the first slide should dictate the slide of the carousel. This MR ensures successive slides only fill the same aspect ratio space as the first slide.
1.  Visit the Jaquemus project page
2. Image carousel slides should all match each other
> Fix jumping carousel image height

- src/components/Video/Video.tsx
- Open the preview link on Safari mac, and mobile browsers
- The videos should autoplay
Note: Make sure your battery is not low, otherwise this will not work.
> Add playsinline to video component

- src/components/Layout/Layout.module.css
- src/components/Video/Video.module.scss
- src/components/Video/Video.tsx
- Remove aspect ratio from the video wrapper (video has inherit size)
- Keep the aspect ratio style on the image placeholder
- Add a white background on the video-js wrapper, seems to help
- On Safari, videos don't have black borders on any side
> fix black line around video on safari

- src/components/HomeVideo/HomeVideo.module.css
- src/components/LazyLoad/LazyLoad.tsx
- src/components/Video/Controls/Controls.tsx
- src/components/Video/Video.tsx
- src/components/Video/useHlsVideo.ts
- src/pages/video/[id]/index.tsx
- Wait for 'manifest' to be ready before trying to play the hls video
- Catch `play()` errors
- Other small adjustments
- The videos should be playing properly on all browsers. 
Please note, this doesn't mean that they ALWAYS autoplay. But if they fail to autoplay, pressing the play button should play them. Nothing should break in that case.
> adjust autoplay

- src/components/Video/Controls/Controls.tsx
- src/components/Video/Video.tsx
- src/types/types.ts
- src/utils/videoUtils.ts
- Use the fallback `720p mp4` file for download. We can't serve to the users a ProRes file to be downloaded (example jacquemus video). The file is too big to be played on a browser, and it lags. And also, safari can't resolve the filename.
- Unfortunately, there's no easy way to "force" a download as soon as you click on a button. It's a browser thing that tries to preview the files first.
> Download link

- src/pages/video/[id]/index.module.css
- src/pages/video/[id]/index.tsx
The back button on the video focus page is not always 100% obvious at first glance, with a small click area.
This MR:
- Makes the whole top 50% of the page background clickable to go back.
- Gives the back button a pulsing opacity animation while hovered, to indicate what behaviour will be triggered when the user clicks
1.  First of all, verify that above statements are true
2. Check that videos still display correctly for: one vertical, one landscape orientation video on desktop; one vertical, one landscape on mobile
> Larger back button click area

- src/components/ProjectDetail/ContentBlock/ContentBlock.tsx
- src/components/Video/Controls/Progress/useMouseHoverPosition.ts
- src/components/Video/Controls/useSharedUnmutedVideoState.tsx
- src/components/Video/Video.tsx
- src/pages/projects/[slug]/index.tsx
- src/pages/projects/[slug]/useScrollRestoration.ts
- src/pages/video/[id]/index.tsx
- src/utils/hooks/useSunset.ts
Fixes two small defects in how video focus mode opens from the project page:
1. Persist mute state – if video is muted, stay muted. If video is unmuted, stay unmuted
2. Scroll restoration – going back to project page from a video will persist the scroll position
It's important to note scroll restoration doesn't work elsewhere on the site, and hasn't for a long time. This needs some attention, wasn't able to solve it this time. Opening the video is the most noticeable case, however.
1.  From a project, open a video and test that above statements are true
> Frictionless video opening

- src/components/Video/Controls/Controls.tsx
- src/pages/video/[id]/index.module.css
Video should never overflow the space allocated for it by CSS grid. Ensure it and its frame have max-width/max-height set.
1.  Open both a landscape and portrait video (there's a portrait video on Jacquemus)
2. Test changing window, verify video is always contained _within_ its frame
> Ensure video has maximum constraints

- src/components/Logo/Logo.module.css
- src/components/Navigation/Navigation.module.css
- src/components/Video/Controls/Controls.tsx
Currently the page header captures all pointer events, which can be confusing as it has a transparent background and spans the full width of the page.
This MR ensures the background does not capture pointer events, but each link does.
1.  Test on mobile and landscape
2.  Scroll and try to click through the background/empty space of the header, the click will hit the element below
3.  Click the logo/studio/project links, the links will work as expected
> Header should not capture all pointer events
