src/components/Layout/global.css, src/components/projectDetail.module.scss
Cards:
- https://trello.com/c/B9SVCuXw/11-homepage-project-list
- https://trello.com/c/nshRswFw/18-pdp-credits-list
- Removed `scroll-behaviour: smooth` due to chrome's bad handling in SPA's
- Correct style assigned for credits and breakpoint
=> Credits n scroll tweaks

src/components/Layout/global.css, src/pages/404.js, src/pages/404.module.scss
Added a simple responsive 404 page
=> Add a responsive 404 page

gatsby-config.js, package-lock.json, package.json, src/components/Layout/layout.js, src/components/Studio/Recruitee/JobOffer/jobOffer.js
Added google analytics. Should only be added to the build when netlify's context is `production`.
Needs to be checked when merged to master
=> G analytics

static/humans.txt, static/robots.txt
Add simple robots.txt and humans.txt
=> Robots txt

gatsby-browser.js, gatsby-ssr.js, package-lock.json, package.json, src/components/SEO/SEO.js
Switch from unmaintained `react-helmet` to actively maintained `react-helmet-async`
=> Switch to react-helmet-async

gatsby-config.js
Reduces image compression during remark processing.
=> Improve image quality

gatsby-config.js, src/templates/Project/Project.js
Import high quality images directly in GraphQL
=> Use new higher quality images on PDP

static/admin/config.yml
Correct the pointer to have the master as back-end
=> Correct the back-end pointer

src/templates/Home/ProjectList/ProjectList.module.scss
Revert commented out .statement class
=> Fix styling of statement block on mobile (regression)

src/components/ProjectDetail/ProjectDetail.module.scss
Correcting (increase) whitespace under the PDP title
=> Fix PDP title marign

src/components/Footer/Newsletter/Newsletter.module.scss
See: https://stackoverflow.com/questions/2918707/turn-off-iphone-safari-input-element-rounding
=> Newsletter email field underline should be line

gatsby-config.js, package.json, src/cms/cms.js, src/site/articles/“body”-using-your-self-as-a-search-tool.md, src/templates/Home/ProjectList/ProjectList.js
CMS should work again, showing an accurate preview.
(Number controls like for image width should still work as well.)
=> Fixing the cms's component errors

src/templates/Home/ProjectList/IntermittentBlock/IntermittentBlock.module.scss
https://trello.com/c/DuUreLWK/115-add-medium-link
=> Fix overlap on intermittend block

src/random-paris/components/Main/Main.js, src/random-paris/components/TakeOverHeader/TakeOverHeader.js
- Allow starting at random points in range x
- stop stats.js
- Sped up the journey speed as we are past the live date
=> RP - Random starting positions for variation after live

src/pages/studio/index.js
- Add new business inquiries email in studio page
=> Add business inquiries email

src/pages/studio/Studio.module.css
=> Amend: "Add business inquiries email"

src/components/ProjectDetail/ProjectDetail.module.scss
https://trello.com/c/t4lVkNrl/283-add-white-space-between-logo-and-text-on-phone
=> Increase verical padding on ProjectDetail component

src/api/addAdditionalInfoToBlocks.js
- If the video component didn't have the old video url, we wouldn't be getting the data for the new video. Added a conditional for that.
=> Add support for newVideo without old video

package.json, src/components/Studio/Block/Block.js, src/styles/global.scss
Improves font sizing of superscript characters (see intro text on Studio page for an example).
* Drops size to 0.75ex (0.75 of x-height)
* Moves position up by 0.25ex
=> Improve superscript font sizing

package.json, src/api/QUERIES.js, src/api/addAdditionalInfoToBlocks.js, src/components/ProjectDetail/ContentBlock/ContentBlock.js, src/components/ProjectDetail/ContentBlock/ContentBlock.module.scss, src/components/ProjectDetail/ProjectDetail.js, src/components/Studio/Block/Block.js
Adds support for inserting blocks in a row.
* Horizontal row block added to Dato
* Image, Text and Video blocks can be embedded within a horizontal row
=> Add horizontal row block

src/styles/global.scss
Sup should never interfere with the line height of the rest of the text.
1.  Have a look at the Studio page intro
2. ?????
3. And you're done
=> Never let sup interfere with line height

src/components/Video/Controls/Controls.tsx, src/components/Video/Video.tsx, src/types/types.ts, src/utils/videoUtils.ts
Reverts RandomStudio/random-studio#214
=> Revert "fix download link"

package.json
Bump next version for correct polyfills
=> Bump next verison

src/api/QUERIES.js, src/components/Head/Head.tsx, src/components/Image/Image.tsx, src/pages/projects/[slug]/index.tsx, src/pages/video/[id]/index.tsx, src/types/types.ts, src/utils/videoUtils.ts
- Add meta tags to video page
- Only the image thumbnail for now. Title and description to be decided, since videos on Bunny don't have such information
- Go to a single video page (focus mode)
- Copy the link
- Share it on social media
- ~~The link should have a nice preview with Title, description, and image from the projeoct~~
- The link should have a nice preview with a thumbnail from the video
=> Video meta tags

src/components/Video/Controls/Controls.module.css, src/components/Video/Controls/Controls.tsx, src/components/Video/Video.tsx
- Add click event to "show controls" text
- On mobile, when tapping on "show controls", it takes you to the video page
=> Handle click on "show controls" text

netlify.toml, src/components/Video/Controls/Controls.module.css, src/components/Video/Controls/Controls.tsx
Redirect `/future-forest` to `/video/fe4a1225-a115-4e7e-9170-402ca2b17b31`
=> add redirect
